version: 2

sources:
  - name: olist
    description: "Raw Olist Brazilian e-commerce data loaded into DuckDB."
    schema: main

    tables:

      - name: customers
        identifier: raw_customers

      - name: orders
        identifier: raw_orders

      - name: order_items
        identifier: raw_order_items

      - name: order_payments
        identifier: raw_order_payments

      - name: order_reviews
        identifier: raw_order_reviews

      - name: products
        identifier: raw_products

      - name: sellers
        identifier: raw_sellers

      - name: category_translation
        identifier: raw_category_translation

      - name: geolocation
        identifier: raw_geolocation